### ISSUE TITLE
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by borisfeldman** [oznu/docker-homebridge#104]
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

Getting this error from the homebridge-config plugin using the "oznu/homebridge:debian" image. Is there package I need to add?

**Comment by oznu** [comment]
Which homebridge-config plugin are you trying to use?

**Comment by borisfeldman** [comment]
Here is the line from the homebridge package.json file:
    "homebridge-config-ui-x": "^3.4.0",

**Comment by borisfeldman** [comment]
A few more notes:

I'm running Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-124-generic x86_64) in a VirtualBox. The same config plug-in works fine in the "oznu/homebridge" docker image [no ":debian" tag] but in that setup, ffmpeg doesn't install.

Thanks for the quick reply and the help! Awesome image, btw.

**Comment by oznu** [comment]
Hi @borisfeldman,

Can you remove the `homebridge-config-ui-x` line from your package.json. Then enable it using these env variables instead?

https://github.com/oznu/docker-homebridge#homebridge-ui-options

`-e HOMEBRIDGE_CONFIG_UI=1`

This will run the ui as a stand-alone process allowing you to still access to ui even if homebridge won't start (due to a bad config for example).

Also make sure you have the most recent version of the image:

```
docker pull oznu/homebridge:debian
```

**Comment by borisfeldman** [comment]
That works! ... and of course I missed it in the really well done documentation. Sorry about that. Mea culpa.
