### ISSUE TITLE
homebridge stopped not working after a while

### ISSUE THREAD

**Issue by MaikelNL** [oznu/docker-homebridge#115]
I'm a newbie at this. I installed homebridge on my sonolgy NAs. Works fine but after a while the homebridge on my iphone stops working. it is not responding and on my iphone it says updating on the lamp switsches. I have installed it and have change a few things but not all of it. so it is the clean install that stops working after a while. i need to restart the docker to let it work again. but thats 3/ 4 times a day. need some help here.. Can anyone help me with this? Let me know how and maybe i can post the script or something..  Grtz Maikel

**Comment by oznu** [comment]
Hi @MaikelNL,

This is a common issue with homebridge - usually caused by low quality plugins not responding to HomeKit correctly which results in the HomeKit ecosystem blocking Homebridge until it's reset.

Similar issues:

```
https://github.com/nfarina/homebridge/issues/1945
https://github.com/nfarina/homebridge/issues/1801
https://github.com/nfarina/homebridge/issues/1668
https://github.com/nfarina/homebridge/issues/1418
https://github.com/nfarina/homebridge/issues/1494
```

Try only using one plugin at a time to see which ones causing the issue; also check each plugins respective GitHub Issue Tracker to see if other users are have similar problems.
