### ISSUE TITLE
Device can't be found in Home app

### ISSUE THREAD

**Issue by ifeign** [oznu/docker-homebridge#125]
I've used your docker setup flawlessly on my personal raspberry pi, but when I tried to install it on my friend's system, even after a clean OS install it doesn't work. Everything starts up correctly according to the log file, but when I go to connect the Homebridge on my phone, it never finds it.

I've scoured the internet, and I suspect it's something to do with IPV6 because his ISP supplied router from Spectrum uses it, but I'm no expert and I'm not sure if this is really the case or the cause of the issue - your setup is the first time I've ever used Docker. To make things more confusing, I have the same ISP but use my own router and have no problems...

Is there a way to turn IPV6 off in Docker? Are there other things I should be looking for?

How would I go about uninstalling this? I wonder if a regular, non dockerized Homebridge install would work and I would like to test that as a last resort.

**Comment by oznu** [comment]
Hi @ifeign,

This container needs to be run  with `host` networking, so the IPv6 settings for docker (which is disabled by default as far as I remember) will not matter, the container will simply inherit any interfaces the host has, including IPv6 ones.

You can try disabling the hosts Avahi daemon, this is the usual culprit. Restart the container after running these commands on the host:

```
systemctl stop avahi-daemon
systemctl disable avahi-daemon
```

Otherwise to remove the container, if you've followed the instructions on the wiki, you can run this command to clean everything up:

```
docker-compose down
```

**Comment by ifeign** [comment]
Thanks for the quick response. I tried your suggestion and still no luck. I’ll upload my log soon for you to review.

**Comment by ifeign** [comment]
It was the router itself. I tested it with another router and the homebridge accessory was found instantly. Made my friend buy a new router to solve this (and a few other unrelated network issues). Thanks for your help.
