### ISSUE TITLE
No-Avahi image still errors when another Avahi instance on network

### ISSUE THREAD

**Issue by mrnoisytiger** [oznu/docker-homebridge#167]
I'm using the no-avahi tag with the Docker image because I have a PfSense router running Avahi. My Homebridge instance is on a separate VLAN, so I need the Avahi daemon on PfSense to traverse it. 

However, when I run the no-avahi image in a fresh install, I get the 

    Error: Service name is already in use on the network

error, as if the docker image is running Avahi.

**Comment by ageorgios** [comment]
is there a recommendation NOT to use macvlan?

**Comment by diamondsw** [comment]
FWIW, I used Macvlan today when setting up Homebridge with no apparent ill effects (using debian-no-avahi).

**Comment by willemdupreez** [comment]
A bit late to the party but I encountered the same error when standing up two instances of homebridge on the same network with the same config (including `name` and `username` in the `$.bridge` section). I updated those to something different and the error disappeared. It may not be the issue here but might help someone else.
