### ISSUE TITLE
Devices show "No response" after latest update

### ISSUE THREAD

**Issue by Danimal4326** [oznu/docker-homebridge#195]
Just updated and homebridge was updated from 0.4.48 to 0.4.49.   Now all my devices are showing up as "No Response" in the Home app.  Worked fine previously.  I can also access the device via curl script I use in "Insecure" mode.

**Comment by oznu** [comment]
You may need to re-pair with Home. Before doing so delete the `persist` and `accessories` directories in your `/homebridge` volume mount, and adjust the `username` and `pin` in the `config.json` to be something new.

**Comment by Danimal4326** [comment]
No luck. Deleted persist and accessories folder.  Deleted add devices from Home app. When trying to add bridge, it just sits there "Searching for Accessory"

**Comment by Danimal4326** [comment]
Ok I think I figured it out.  Seems with the latest update, when I have my VPN enabled on the synology, the Home app cant find homebridge.  As soon as I disable it, everything is fine.  

In the previous version, this was working (VPN on and homebridge running on docker.) I enabled the multiple gateways feature in Synology to make this work.  Not sure what changed, but Its not working for me anymore.

**Comment by ifeign** [comment]
I too am having connection issues with all my accessories not responding. I just finished a clean install of raspbian but still no luck.

**Comment by nautipuss** [comment]
I've been having this issue as well, although not sure if it's since the last Synology DSM update or the HomeBridge update, as they were at similar times. As with others, switching the VPN off solves the problem, and turning the VPN on leads to accessories saying "No response", HomeBridge included.

I've played around with the VPN settings and Gateway settings to no avail. Nothing works so far and I want to keep the VPN running.

**Comment by GreatCookie** [comment]
Just adding my general comments as well as i'm not sure where the problems actually stem from.

@oznu: Firstly, thanks for the absolute BEAST of code you've developed; Homebridge running on Docker (and the Config-UI-X) has literally changed my household over the last 12 months for the absolute better. 81 Devices and counting and my Family and I couldn't be happier - so sincerely a BIG THANK YOU!

**Back on-topic:** After installing the latest copy of DSM (I'm running in Docker on Synology NAS) as well as Homebridge about three weeks ago, have been getting weird errors for what was a rock-solid setup for about 5months.

My first issue (serious) was that the Alexa plugin was causing a SIGTERM infinite reboot of the homebridge instance. I literally had to remove the plugin and wait for the update before that would work again.

The second persistent issue that i'm having is that for the Chuangmi-IR remote plugin [,](https://github.com/WestCoast5550/homebridge-mi-ir-remote) I generally have no problems sending the command via the homebridge-config-ui-x (a great UI) under Accessories tab, but triggering the switch from an iOS device in the Home App will result in the switch then displaying the spinning wheel (sometimes sending the command, othertimes not in the real world) resulting in all other homebridge switches to then then 'seize' and not respond - as if Home or Homebridge was waiting for a confirmation from the device for a state change before proceeding.

The only thing is that I'm unable to figure out where the problem stems from. I kind of suspect it is a DSM issue - but with so many updates recently (including Docker), it's kind of hard to trace where the root cause lies.

OT: Like @nautipuss, i've always had the issue of VPN connection (in Synology) screwing with the Homebridge instance. I've kind of gotten use to switching off the VPN when not required.
