### ISSUE TITLE
Updating Homebridge Procedure (docker)

### ISSUE THREAD

**Issue by Ipnotik** [oznu/docker-homebridge#198]
Hello Oznu. I'm trying to update homebridge to the latest version by following your procedure.

> To update to the latest version of Homebridge and the oznu/homebridge container:
> 
> Download the latest version of Homebridge
> On the Container tab stop the existing Homebridge container
> Edit the existing container and change it's name to homebridge-old
> Select homebridge-old then click Settings then Duplicate settings
> Name the container homebridge
> Start the homebridge container
> Delete the homebridge-old container

Problem is that something seems to be missing in the procedure because after I downloaded the latest version if I follow the other steps I just re-run the old version. Indeed there is no description about how to start the installation of the latest downloaded container. I'm in confusion...please help!

Thanks,
L

**Comment by oznu** [comment]
The steps may be out of date (I don't run my instance on the Synology anymore), deleting everything in the Docker app and recreating the container should work, if you point it to the same volume mount you won't loose any settings doing this.

Otherwise this package makes it easy to stay up to date: https://github.com/oznu/homebridge-syno-spk

**Comment by Ipnotik** [comment]
Great! Thanks.

**Comment by themfinger** [comment]
Hi.

Is there any benefit of installing the homebridge-syno-spk if the default
docker version works well?

What does the package add to the normal way?

Thanks!
