### ISSUE TITLE
Installation on Raspberry Pi / Stretch

### ISSUE THREAD

**Issue by qnm** [oznu/docker-homebridge#20]
Hi

I've just installed this image on a RasPi with Stretch, and the Docker installation is a little different.

Is it worth updating the docs, or creating a version for Stretch?

**Comment by oznu** [comment]
Thanks for pointing this out.

I think keeping the guide up-to-date for the latest release of Raspbian is the best way to go. The guide is aimed at users performing a fresh install so it's probably of little value retaining the instructions for Debian Jessie. Feel free to update the wiki; otherwise I'll do it in the next couple days.

**Comment by CyrusSUEN** [comment]
@qnm What went wrong during the Docker installation?

Is it the part installing with `pip`?
You can try to replace the following pip for pip3, which worked for me.
`sudo apt-get -y install python-setuptools && sudo easy_install pip3  && sudo pip3 install docker-compose`

**Comment by oznu** [comment]
Updated the guide for Raspbian Stretch.

* Included details on setting up a headless Raspberry Pi (ssh and wifi setup without connecting a screen).
* Instructions updated to install docker using official method for Stretch,  using the `curl -sSL https://get.docker.com | sh` command was depreciated as it installs `docker-engine` not `docker-ce`.
* Updated plugin installation instructions.

**Comment by oznu** [comment]
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi/_compare/f76b6e0d179abc5689f1b0a965d764180de630d4...f2d27230a6b0c897416911c57d61046eb98fde05
