### ISSUE TITLE
The repository 'https://download.docker.com/linux/raspbian 10 Release' does not have a Release file

### ISSUE THREAD

**Issue by Nicode70** [oznu/docker-homebridge#209]
Hi! i'm trying to do a fresh install of home bridge and i get this message:

The repository 'https://download.docker.com/linux/raspbian 10 Release' does not have a Release file.

I've tried both the quick and the manual options. 

Could you please help me?

thanks.

**Describe Your Problem:**

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:

**Comment by oznu** [comment]
It looks like buster is not yet supported by Docker as it was only published a few days ago.

Use Stretch instead: http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/

**Comment by Nicode70** [comment]
Thank you very much. it worked. I really love homebridge. 
thank you for your effort

**Comment by johnsonjoshuaa** [comment]
For those with a Pi4 waiting for the buster release, it is now building in the nightly folder. Here are some instructions on how to successfully run docker-ce and docker-compose on a Pi4. I have been working on this since the Pi4 released, and this finally worked for me. I hope it is
 helpful for anyone else looking for a solution. 

curl -fsSL https://get.docker.com -o get-docker.sh
chmod u+x get-docker.sh
sudo nano ./get-docker.sh
	change the $channel value at the top of the file from "stable" to "nightly"
sudo ./get-docker.sh
sudo usermod -aG docker pi && logout
sudo apt-get install python3-pip
sudo apt-get -y install docker-compose


Follow instructions for the rest. 

I have attached a screenshot showing the "$CHANNEL" value that needs to be changed in ./get-docker.sh

Also attached a screenshot of the webui showing the 4GB of resources. 
![Screen Shot 2019-07-16 at 6 08 38 PM](https://user-images.githubusercontent.com/52268841/61336132-c37bb000-a7f5-11e9-90f0-32c7230e2b58.png)
![Screen Shot 2019-07-16 at 6 18 33 PM](https://user-images.githubusercontent.com/52268841/61336248-4270e880-a7f6-11e9-9cbc-9ba22732d736.png)

**Comment by RaymondMouthaan** [comment]
Meanwhile Docker is available for Raspbian Buster (https://download.docker.com/linux/raspbian/dists/buster/)

**Comment by oznu** [comment]
Thanks for the update @RaymondMouthaan. I'll give it a test and update the wiki.

**Comment by oznu** [comment]
The wiki and the quick install script have been updated.
