### ISSUE TITLE
Docker & Homebridge

### ISSUE THREAD

**Issue by jeylites** [oznu/docker-homebridge#21]
Not a issue... What is the benefit of running docker with homebridge? I'm new to docker and I'm trying to understand it's function in a project like this.

**Comment by oznu** [comment]
This container allows the Homebridge application to be packaged with all of the parts it needs, such as libraries and other dependencies, ship it all out as one package, and run isolated to other services on the same machine.

For armhf users on low spec boards (Raspberry Pi), it's quicker to get up and running since certain Homebridge dependencies require compiling - which can take a long time on a 700MHz CPU. When using this Docker image those dependencies are shipped pre-compiled.

For me personally, I use Docker containers to run Plex, a DNS server, Nginx, a UniFi Controller and half a dozen more apps on the same host, so running Homebridge in a container as well kept things simple and portable.

**Comment by VeniceNerd** [comment]
Which Docker image did you use for the UniFi controller? :)

**Comment by oznu** [comment]
@VeniceNerd I use the image developed by [LinuxServer.io](https://tools.linuxserver.io/dockers) for the UniFi Controller.
