### ISSUE TITLE
Do homebridge-config-ui updates delete personal plugins?

### ISSUE THREAD

**Issue by ceraz68** [oznu/docker-homebridge#255]
**Describe Your Problem:**
I run the docker on Synology. I installed my personal test plugin (homebridge-security-mailer) in /homebridge/node_modules along with the public plugins installed from Github. It has now been deleted from the node_modules directory.

The plugin was visible in the config UI plugin window. I did not declare my homebridge-security-mailer plugin in /homebridge/package.json as a dependency 

I suspect my plugin was deleted as it was not declared as a dependency in /homebridge/package.json. It seems to be related to config ui update from 4.6.3 to 4.6.4.

Does config-ui-x clean up the node_modules directory? would I need to declare my test plugin in package.json ?

Thanks a lot !

**Logs:**

Before update: the plugin is loaded

[37m[12/1/2019, 10:31:33 PM][39m ---
[0;37m[12/1/2019, 10:31:33 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.6.3 is listening on :: port 8581[0m
[37m[12/1/2019, 10:31:49 PM][39m Loaded plugin: homebridge-security-mailer
[37m[12/1/2019, 10:31:49 PM][39m Registering accessory 'homebridge-security-mailer.security-mailer'

After update: the plugin is not listed

[0;37m[12/1/2019, 11:06:08 PM] [0m[0;36m[Config][0m Changes to config.json saved.
[0;37m[12/1/2019, 11:07:27 PM] [0m[0;36m[Config][0m Restarting the docker container, make sure you have --restart=always turned on or the container will not come back online
[0;37m[12/1/2019, 11:15:21 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.6.4 is listening on :: port 8581[0m

**Docker Start Command:**
I use the config-ui-x restart button (instead of restarting the container in the Synology docker)

**Environment:**
* **Node.js Version**: v12.13.0
* **NPM Version**: 6.12.0
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.6.4
* **Operating System**: Synology Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
Hi @ceraz68,

I moved this issue to oznu/docker-homebridge as this is caused by the docker container restarting, not homebridge-config-ui-x.

When the docker container starts, or restarts, the `package.json` is read and the container makes sure all the plugins listed in this file exist, and any ones that don't are removed. To prevent this from happening, adding the package to the package.json should work.

Alternatively you could also install your custom plugins like this:

1. Pack the plugin by running `npm pack` in the plugin source code directory. This will create a `homebridge-security-mailer-1.0.0.tgz` file containing the entire module (it's the same as what would be published to npm).
2. Transfer the `homebridge-security-mailer-1.0.0.tgz` to the `/homebridge` directory in your docker container.
3. Install the module from the `.tgz` directly by running `npm install homebridge-security-mailer-1.0.0.tgz` (do this from inside the container).
4. Leave the `.tgz` in the `/homebridge` directory so the container can reinstall the plugin if it ever needs to.
5. You will notice the `package.json` has automatically been updated to include a line that looks like this:
    * `"homebridge-security-mailer": "file:homebridge-security-mailer-1.0.0.tgz"`
6. You can now safely restart the docker container without losing any personal plugins.

**Comment by ceraz68** [comment]
Hi Oznu, sorry I couldn't respond earlier. This is a fantastic "how to".

I experimented different approaches  but your works like a treat!

Happy new year :-)
