### ISSUE TITLE
Installation of plugin from tar.gz file fails

### ISSUE THREAD

**Issue by HammerAce42** [oznu/docker-homebridge#258]
(filing as a new issue in case responses to closed issues aren't monitored)

When trying to install a plugin directly from a tar.gz file per instructions [posted here](https://github.com/oznu/docker-homebridge/issues/254#issuecomment-562915302), installation fails with numerous errors: 

```
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm5/internal/operators/index.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/internal/operators/index.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/operators/index.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm2015/internal/InnerSubscriber.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm5/internal/InnerSubscriber.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/internal/InnerSubscriber.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm2015/internal/observable/interval.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm5/internal/observable/interval.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/add/observable/interval.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/internal/observable/interval.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/observable/interval.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/observable/IntervalObservable.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm2015/internal/util/isArray.js'
npm WARN tar ENOENT: no such file or directory, open '/homebridge/node_modules/.staging/rxjs-00ce25b2/_esm5/internal/util/isArray.js'
```

Installation of the plugin after uncompressing the tar.gz file succeeds, but gets overwritten when Homebridge restarts.

**Comment by oznu** [comment]
@adriancable @chrisjshull https://github.com/chrisjshull/homebridge-nest/issues/148

I've noticed a few people having issue installing the experimental package, I think the issue is to do with how the .tar.gz is being generated.

You can distribute an npm package as a .tar.gz that can be installed without having to extract it first by running the `npm pack` command in the project root. This command works just like the `npm publish` command except it generated a local `.tar.gz` file instead of publishing it to the npm registry.

Once this .tar.gz file has been created using the `npm pack` command, users can install the package easily:

```shell
# linux
sudo npm install -g homebridge-nest.tar.gz

# docker
npm install homebridge-nest.tar.gz
```

**Alternatively**, and this is the way I prefer to do it, you can publish test and beta packages to npm using an alternate tag.

For example, if I publish a package like this:

```
npm publish --tag=experimental
```

Users will be able to install this test version like this:

```
sudo npm install -g homebridge-nest@experimental
```

You'll need to bump the version in your package.json each time, I like to prefix mine like `4.0.0-beta.1` as once `4.0.0` is published to the untagged package any users still using the betas will see an update available.

Users can roll back just be installing the none-tagged version (i.e `latest`):

```
sudo npm install -g homebridge-nest
```
