### ISSUE TITLE
raspberry pi 3 GPIO

### ISSUE THREAD

**Issue by cbnorman** [oznu/docker-homebridge#47]
not sure if this is even possible, relatively new to containers/docker. i am trying to use the GPIO pins from with the container to activate a switch, similar to documented here https://spin.atomicobject.com/2017/08/27/siri-homekit-raspberry-pi-software/. is it possible to access/control the gpio from within the container? most options seem to require https://pypi.python.org/pypi/RPi.GPIO but im unable to pip install or yarn add within the container?

**Comment by oznu** [comment]
It is possible to access the GPIO pins on a Raspberry Pi inside a Docker container with a few config changes, but I think you'll find it's not going to be easy with this container for a few reasons:

* This container is running Alpine Linux, many of the Pi libraries will be expecting Raspbian.
* This container does not run Homebridge as a privileged user, such as root, which is often required for GPIO access.

I would recommend installing Homebridge directly on the Raspberry Pi and using systemd to manage the service.

**Comment by joelsdc** [comment]
This is funny.. I was about to create this same ticket twice, but I thought I had to be doing something wrong. I haven't got to the testing point yet, but I have read in multiple places that you need to export the GPIO you want available in user space, that way docker and/or unprivileged users "should" be able to access them.

**Comment by joelsdc** [comment]
Example:

Say you need GPIO pins 4, 6, 8 available in your docker image, try this:

echo "4" > /sys/class/gpio/export
echo "6" > /sys/class/gpio/export
echo "8" > /sys/class/gpio/export

Then check the logs in docker to see if you are still getting the `permission denied` or `file not found` errors...

There is a tool that is widely used too: http://wiringpi.com/the-gpio-utility/

You can use it too to export GPIO pins... You will probably have to do this automatically on boot, otherwise if you reboot the Pi everything will stop working.

I hope to have some time to test this out this weekend, I'll update here if I find a solution, if not, as @oznu said, we will have to go with homebridge directly.
