### ISSUE TITLE
Config plugin doesn't work by default or when configured

### ISSUE THREAD

**Issue by AlphaCluster** [oznu/docker-homebridge#50]
By default when the config ui is enabled nothing starts up. I added the plugin and I just keep getting this error:
[2018-1-13 20:21:20] Error: Cannot find module '../build/Release/pty.node'

When I disable the config ui I no longer continue to get the errors but for some reason it still happens once while starting up which also seems fairly odd.

**Comment by oznu** [comment]
By "config ui" do you mean the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) plugin?

If so are you enabling this using the `-e HOMEBRIDGE_CONFIG_UI=1` option at startup or by loading this plugin using the `package.json` + `config.json` files?

If you have not already I'd recommend trying to delete your local `/homebridge/node_modules` folder and checking the `package.json` file does not have `homebridge-config-ui-x` listed.

**Comment by AlphaCluster** [comment]
So when I installed the synology app for it it (I was using your spk originally) it was throwing the error and no page would show up. So it tried adding it to the config and package and the error would but at least i started getting a page. I tried dumping the node_modules and enabling via the env variable and I still get no page and continual errors.

**Comment by oznu** [comment]
@AlphaCluster - I have pushed a new image that comes with the required `pty.node` binaries pre-built - rather than building them on the fly if `-e HOMEBRIDGE_CONFIG_UI=1`.

If you're still running the SPK you can get the latest image by simply stopping and starting the app in Package Center.

The SPK also sets the port for the UI to `8581` not `8080` since the later is used by [other third party spks](https://github.com/SynoCommunity/spksrc/wiki/SynoCommunity-Used-Ports).

Let me know if this solves the issue.
