### ISSUE TITLE
Setting MAC address on net0 interface

### ISSUE THREAD

**Issue by jwilson2899** [oznu/docker-homebridge#567]
### Current Situation

I have successfully setup Homebridge on my Truenas Scale machine, and everything is running as expected. My question is that there are 2 interfaces. The one on net0, which is the one that actually talks to my network is the one I'm interested in. Since it uses DHCP, it's pulling the address from my router, which is fine. The problem is that every time the container restarts, this interface gets a new MAC address, which causes the router to issue it a different IP address. This makes it a bit hard to keep up with which address I can currently access the Homebridge GUI from when I need to update plugins. Is there some way I can make this interface have the same MAC address every time? Thanks in advance for your help.

### Docker Config

```yml
N/A
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64

**Comment by NorthernMan54** [comment]
This is more of a docker question

But if you use the 'Discovery' app, you should be able to determine the .local address used by the homebridge instance.  And you can use that for access instead of the IP.


ie 
![image](https://github.com/homebridge/docker-homebridge/assets/19808920/f879070a-6e57-4961-8030-60b2e0ed71db)

url would be http://hue-b509.local:8581

**Comment by jwilson2899** [comment]
I fixed by changing the setting in step 5 under the instructions from DHCP to a static IP. Now the container starts each time with a fixed IP address, so I know where to access it.
