### ISSUE TITLE
Can’t install new plugin via config-ui-x

### ISSUE THREAD

**Issue by VeniceNerd** [oznu/docker-homebridge#64]
I wondering if installing plug ins via the Config-UI-X interface is not possible? If I try to install a plugin via the web interface I get the following error message:

![4be38a3d-f2cc-4d6b-af78-f72356533afe](https://user-images.githubusercontent.com/25128243/35831966-5bb58054-0a80-11e8-882f-6a32042d3bba.jpeg)

Installing plugins via the terminal (yarn) works. Would love to be able to install plugins right from the web GUI, though!

**Comment by oznu** [comment]
I think that screen shot tells me homebridge-config-ui-x is not running inside this Docker image? Can you post your config / setup.

**Comment by oznu** [comment]
Disregard the last post. I figured out what you've done 😄 

When running `homebridge-config-ui-x` inside the oznu/homebridge you should activate it using the `-e HOMEBRIDGE_CONFIG_UI=1` flag and remove any related config from your `config.json`.

**Comment by oznu** [comment]
@VeniceNerd - thanks for pointing out this odd behavior. It was caused by configuring the plugin using the `config.json` but using the global install of `homebridge-config-ui-x` which is only suppose to be used when enabling the UI via the `HOMEBRIDGE_CONFIG_UI=1` option. This resulted in the plugins being installed in the wrong location as by default `homebridge-config-ui-x` will attempt to install plugins in the same location it itself is installed.

The latest image I pushed will prevent users setting it up this way. You'll either need to use the `HOMEBRIDGE_CONFIG_UI=1` option or add `homebridge-config-ui-x` using the `yarn add homebridge-config-ui-x` command. It also means the `homebridge-config-ui-x` plugin won't get loaded (*it would never activate unless requested*) for the thousands of other people that aren't using it.

**Comment by VeniceNerd** [comment]
Hey @oznu thanks for looking into this! So what steps do I need to take to fix this on my end now? Remember I have three Docker Containers with three Hoembridge instances running. So I do believe that I need to use the confi.json to give each of them a different port, no?

Do I need to deinstall the plugin now? Then update OZNU/Dcocker? Then re-install Config-UI-X via yarn? Any way you could give me step by step instructions so I don't mess this one up? ;)

Thanks!

Philipp

**Comment by oznu** [comment]
Hi @VeniceNerd,

1. Remove `homebridge-config-ui-x` related config from `config.json`
2. `Modify docker-compose.yml` to include `HOMEBRIDGE_CONFIG_UI=1` and `HOMEBRIDGE_CONFIG_UI_PORT=8080` in the `environment` section (same place you have `TZ`, `PUID` etc.)
3. `docker-compose pull`
4. `docker-compose up -d`

You can also choose which color theme you want using `HOMEBRIDGE_CONFIG_UI_THEME=blue`, it might be useful to use different colors for each instance.

**Comment by VeniceNerd** [comment]
@oznu thank you! Do I also need to deinstall the current config-ui-x plugin via yarn after I remove it from the config.json?

Thanks!

Philipp

**Comment by oznu** [comment]
You should.

**Comment by VeniceNerd** [comment]
Thank you! I finally had time to update all of this. Will test soon if I can now install plugins via the web interface. Gonna need to figure out another issue first, though. (will make a separate post!)

**Comment by VeniceNerd** [comment]
All working well now btw. Thanks for the help.
