### ISSUE TITLE
homebridge-people not working

### ISSUE THREAD

**Issue by glassbase** [oznu/docker-homebridge#69]
Thanks for the work you do for this docker. I like the web interface feature. 

I recently had my homebridge installed in a Lubuntu install. Switched over to docker since it is easier to mange config files and updating, etc. This was all working fine before my switch (of course, that is how it also goes). Using exact same config and config has to errors. I do not believe this is an issue with the plugin, since it worked fine like previously mentioned. 

Container can ping my resolve DNS name and ping device ok, see below:
```
docker exec -it homebridge ping xxxxxxxxx.xxxxxx.net
PING xxxxxxxxx.xxxxxx.net (10.0.0.107): 56 data bytes
64 bytes from 10.0.0.107: seq=0 ttl=64 time=105.091 ms
64 bytes from 10.0.0.107: seq=1 ttl=64 time=26.441 ms
64 bytes from 10.0.0.107: seq=2 ttl=64 time=50.085 ms
```

Tried both IP and hostname in config for testing, still no go. 
```
        {
            "platform": "People",
            "threshold": 15,
            "anyoneSensor": true,
            "nooneSensor": false,
            "webhookPort": 51828,
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "xxxxx",
                    "target": "10.0.0.107",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "xxxxx",
                    "target": "xxxxxxx.xxxxx.net",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
```

Any other info needed, let me know.

**Comment by oznu** [comment]
Hi @glassbase,

There are two issues here. The first is the user which Homebridge runs as did not have permission to run ping. I'll fix this problem in an update to this image.

Test file (this is pretty much what makes `homebridge-people` works):

```js
const ping = require('ping')

ping.sys.probe('192.168.1.68', (state) => {
  console.log(state)
})
```

Test results, running the latest version of `ping` as the Homebridge user:

```shell
# install latest ping library
npm install ping@latest

# test before fixing permissions
/homebridge $ s6-setuidgid abc node test.js
false

# test after fixing permissions
/homebridge $ chmod 4755 /bin/ping
/homebridge $ s6-setuidgid abc node test.js
true # <-- Success
```

The second problem is that this only works on a newer version of the `ping` library than `homebridge-people` ships with. The plugin ships with version `0.1.10` while the latest version is `0.2.2`. If I do the same tests using version `0.1.10` they always fail.

Test results, running the version  0.1.10 of `ping` as the Homebridge user:

```shell
# install ping version 0.1.10
npm install ping@0.1.10

# test before fixing permissions
/homebridge $ s6-setuidgid abc node test.js
false

# test after fixing permissions
/homebridge $ chmod 4755 /bin/ping
/homebridge $ s6-setuidgid abc node test.js
false
```

This second issue can only be fixed by the plugin author updating the dependencies in their `package.json`: 

https://github.com/PeteLawrence/homebridge-people/blob/f27609d4a14722ed74fb376b92c7b11e603ae3c3/package.json#L19

**Comment by glassbase** [comment]
Well thanks for investigating. Going to get presence to work in HA and push that into HB.

**Comment by oznu** [comment]
Permissions for `/bin/ping` have been fixed in the latest build.
