### ISSUE TITLE
UI Not loading on Synology

### ISSUE THREAD

**Issue by behold81** [oznu/docker-homebridge#84]
I have tried adding both environment variables and it fails with a fatal error Unable to exec homebridge-config-ui-x: no such file or directory exists. 

I have tried installing th ui as well and neither options work. 

Thoughts?

**Comment by oznu** [comment]
Hi @behold81, 

Can you provide the entire container log please?

**Comment by oznu** [comment]
Hi @behold81,

I figured out how this happened. I'm guessing you edited the existing container to add the `HOMEBRIDGE_CONFIG_UI=1` environment variable?

The official way to add a docker an environment variable to a container is to delete it and recreate with the new variables set. It looks like the Synology DSM Docker app does something else and injects the variables into the existing containers rather than creating a new container with the same settings. I'm not sure how they are doing this.

The problem with this is, the first time this container is launched it checks for the `HOMEBRIDGE_CONFIG_UI=1` environment variable and if it is not set it removes `homebridge-config-ui-x` to prevent it being loaded by homebridge for users that don't want it. If Synology was doing things the conventional way, this wouldn't be a problem, since changing this variable would mean a new container would be created.

The immediate solution to your problem is to recreate the container and set the environment variable before you launch the container for this first time. You shouldn't loose any settings or config doing this because everything important is stored in your volume mount.

**Comment by behold81** [comment]
Yes. I actually did just this and it did fix it when you playing last night. 

Clear and deleting files was not enough apparently. 

It is worth this being put in the Synology install. 

Thanks. Good to know I was not going mad!
